--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-24-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_STUDENT
--------------------------------------------------------
DROP TABLE "USER4"."TBL_STUDENT";
  CREATE TABLE "USER4"."TBL_STUDENT" 
   (	"ST_NO" CHAR(3 BYTE), 
	"ST_NAME" NVARCHAR2(30), 
	"ST_ADDR" NVARCHAR2(50), 
	"ST_GRADE" NUMBER(1,0), 
	"ST_HEIGHT" NUMBER(3,0), 
	"ST_WEIGHT" NUMBER(3,0), 
	"ST_NICK" NVARCHAR2(20), 
	"ST_NICK_REM" NVARCHAR2(50), 
	"ST_DEP_NO" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER4TS" ;
REM INSERTING into USER4.TBL_STUDENT
SET DEFINE OFF;
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('001','조용필',null,4,166,56,'작은거인','작은 체구 불구 폭발적인 가창력 때문에','001');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('002','임성훈',null,4,168,null,null,null,'002');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('003','이수만','SM엔터테인먼트',4,null,null,null,null,'001');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('004','임예진',null,3,null,null,null,null,'003');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('005','원미경',null,3,null,null,null,null,'004');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('006','박수홍',null,2,183,65,'허우대','키가 큰 것을 비유하여','005');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('007','안칠현','SM엔터테인먼트',1,178,65,null,null,'006');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('008','김태희',null,1,165,45,'헤드뱅잉','수업시간에 졸때 낙차가 너무 커서','001');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('009','한채영','스타제이엔터테인먼트',1,172,47,'바비인형','시원하게 생긴 서구적인 마스크 때문에','002');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('010','박수애','스타제이엔터테인먼트',1,168,46,'리틀 정윤희',null,'006');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('011','허영란',null,1,162,43,'까치','눈동자가 까치 닮아서','005');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('012','정윤호','SM엔터테인먼트',1,184,66,'꼬비',null,'004');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('013','권보아','SM엔터테인먼트',1,162,45,null,null,'001');
Insert into USER4.TBL_STUDENT (ST_NO,ST_NAME,ST_ADDR,ST_GRADE,ST_HEIGHT,ST_WEIGHT,ST_NICK,ST_NICK_REM,ST_DEP_NO) values ('014','문근영','나무엑터스',1,165,45,'국민 여동생','귀여운 여동생 이미지 때문에','002');
--------------------------------------------------------
--  DDL for Index SYS_C007011
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER4"."SYS_C007011" ON "USER4"."TBL_STUDENT" ("ST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER4TS" ;
--------------------------------------------------------
--  Constraints for Table TBL_STUDENT
--------------------------------------------------------

  ALTER TABLE "USER4"."TBL_STUDENT" ADD PRIMARY KEY ("ST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USER4TS"  ENABLE;
  ALTER TABLE "USER4"."TBL_STUDENT" MODIFY ("ST_DEP_NO" NOT NULL ENABLE);
  ALTER TABLE "USER4"."TBL_STUDENT" MODIFY ("ST_GRADE" NOT NULL ENABLE);
  ALTER TABLE "USER4"."TBL_STUDENT" MODIFY ("ST_NAME" NOT NULL ENABLE);
