-- 여기는 관리자 화면입니다.

CREATE TABLESPACE user6Ts
DATAFILE 'C:/bizwork/mydb/user5Ts.dbf'
SIZE 100M AUTOEXTEND ON NEXT 100k;

CREATE USER user6
IDENTIFIED BY 1234
DEFAULT TABLESPACE user6Ts;

GRANT DBA TO user6;